name: Node tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test-main:
    name: Run lib tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install --frozen-lockfile
    - run: yarn test


  test-example:
    name: Run example App tests
    needs: [test-main]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install --frozen-lockfile
      working-directory: example
    - run: yarn test
      working-directory: example


  test-example-in-local:
    name: Run example App in local folder
    needs: [test-main, test-example]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn install --frozen-lockfile
    - run: yarn install --frozen-lockfile && yarn install:local && yarn sync
      working-directory: example
    - run: yarn test App.test.js
      working-directory: example
